

services:
  pg_sus_prenatal:
    image: postgres:15
    container_name: pg_sus_prenatal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sus_prenatal
    ports:
      - "5432:5432"
    volumes:
      - pg_sus_prenatal_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_sus_prenatal_data:
